export const dashboardLocators = {
  tagboardsIframe: "#tagboards > iframe",
  newTagboardButton: ".toolbar button",
  nameInput: "input[name='name']",
  descriptionInput: "input[name='description']",
  createTagboardButton: ".modal-footer .btn-primary",
  tableRows: ".table tr",
  tagboardTitle: ".tagboard-title",
  themesButton: ".user-theme-tab",
  myThemesIframe: "#my-themes > iframe",
  newThemeButton: ".toolbar a",
  chooseThemes: ".choose-theme",
  themeTitleInput: ".sidebar-content input[type='text']",
  saveThemeButton: ".sidebar-content .save-changes",
  themeTitle: ".theme-details .title",
  panelButton: ".user-admin-tab",
  panelIframe: "#smart-panels > iframe",
  newPanelButton: ".toolbar a",
  choosePanel: ".choose-panel",
  panelTitleInput: ".sidebar-content input[name='title']",
  savePanelButton: ".sidebar-content .save-changes",
  panelTitle: ".panel-details .title",
};
